
# Dataset dir
dataset_path: C:\Users\quekz\OneDrive\Desktop\Yolov8-for-Object-Detection-on-LTA-Traffic-Camera-feeds\data #Absolute path to data
train: images/train # train images (relative to 'dataset_path')
val: images/train # val images (relative to 'dataset_path')

# Set your classes
names:
  0: cars
  1: 