from dash import Dash, dcc, html, Input, Output, callback
from components.tab_component import build_bus_stop_tab, build_bicycle_parking_stops_tab, build_taxi_stands_tab, build_carpark_tab, build_traffic_cctv_tab, build_default_display

# Define callback when tabs are selected
@callback(
    Output('tab-content', 'children'),
    Input('multi-tabs', 'value')
)
def render_content(tab: str) -> html.Div:
    """Function which render content based on tab selection on Dash's tab component assisted by dash callback implementation.
    
    Args:
        tab (str): Tab value based on selection on screen

    Returns:
        html.Div: HTML Division generated by function call based on tab option selected. 
    """
    if tab == 'bus-stop-tab':
        return build_bus_stop_tab()
    elif tab == 'bicycle-tab':
        return build_bicycle_parking_stops_tab()
    elif tab == 'taxi-stand-tab':
        return build_taxi_stands_tab()
    elif tab == 'carpark-tab':
        return build_carpark_tab()
    elif tab == "traffic-cctv-tab":
        return build_traffic_cctv_tab()
    else:
        return build_default_display()